<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMtzht7p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMtzht7p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMtzht7p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMtzht7p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMtzht7p\appDevDebugProjectContainer([
    'container.build_hash' => 'Mtzht7p',
    'container.build_id' => 'ad1ef6d8',
    'container.build_time' => 1582640999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMtzht7p');
