user:
<<<<<<< HEAD
    resource: "@UserBundle/Resources/config/routing.yml"
=======
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /a

opportunity:
    resource: "@OpportunityBundle/Controller/"
    type:     annotation
>>>>>>> dfd40a50d5e94cfc507b4f4a4b8d231355233b8b
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
<<<<<<< HEAD
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
=======
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
>>>>>>> dfd40a50d5e94cfc507b4f4a4b8d231355233b8b
