security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_VOLONTAIRE:       ROLE_USER
        ROLE_ASSOCIATION:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
<<<<<<< HEAD
=======
        in_memory:
            memory: ~
>>>>>>> dfd40a50d5e94cfc507b4f4a4b8d231355233b8b
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
<<<<<<< HEAD
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
=======
        - { path: ^/front, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_LIVREUR:     ROLE_LIVREUR
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_RH:          ROLE_RH
>>>>>>> dfd40a50d5e94cfc507b4f4a4b8d231355233b8b
