<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwwo3ww\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwwo3ww/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKwwo3ww.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKwwo3ww\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKwwo3ww\appProdProjectContainer([
    'container.build_hash' => 'Kwwo3ww',
    'container.build_id' => 'f8f0c856',
    'container.build_time' => 1581495996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwwo3ww');
