project_opportunity:
    resource: "@ProjectBundle/Resources/config/routing/opportunity.php"
    prefix:   /opportunity

project_postulations:
  resource: "@ProjectBundle/Resources/config/routing/postulations.php"
  prefix:   /postulations

project_homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }
evenement_show:
  path:     /evenement_show
  defaults: { _controller: ProjectBundle:Default:show }