<?php

namespace ProjectBundle\Repository;
use ProjectBundle\Entity\Postulations;
/**
 * PostulationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOpsByIdUsrIdOp($idUser,$idOp)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
        FROM ProjectBundle:Postulations p
        WHERE p.id_user = :idUser AND p.idOp = :idOp')
            ->setParameters(array($idUser => 'idUser', $idOp => 'idOp'))
            ->getResult();

    }

    public function getCustomInformations($id)
    {
        $rawSql = "select postulations.id_user,opportunity.nomOp from postulations,opportunity where opportunity.idAssoc = ".$id." AND opportunity.id = postulations.idOp";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }
}
