project_donation:
    resource: "@ProjectBundle/Controller/DonationController.php"
    type:     annotation

project_demande:
    resource: "@ProjectBundle/Controller/DemandeController.php"
    type:     annotation

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

