<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6c3vgaf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6c3vgaf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6c3vgaf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6c3vgaf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6c3vgaf\appDevDebugProjectContainer([
    'container.build_hash' => '6c3vgaf',
    'container.build_id' => 'f2d131c8',
    'container.build_time' => 1582035599,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6c3vgaf');
