<?php

namespace Proxies\__CG__\ProjectBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Donation extends \ProjectBundle\Entity\Donation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'id', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'userDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'demandeDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'typeDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'etatDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'quantiteDonation'];
        }

        return ['__isInitialized__', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'id', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'userDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'demandeDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'typeDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'etatDonation', '' . "\0" . 'ProjectBundle\\Entity\\Donation' . "\0" . 'quantiteDonation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Donation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatDonation($etatDonation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatDonation', [$etatDonation]);

        return parent::setEtatDonation($etatDonation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatDonation', []);

        return parent::getEtatDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteDonation($quantiteDonation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteDonation', [$quantiteDonation]);

        return parent::setQuantiteDonation($quantiteDonation);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteDonation', []);

        return parent::getQuantiteDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDonation', []);

        return parent::getUserDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDonation($userDonation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDonation', [$userDonation]);

        return parent::setUserDonation($userDonation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeDonation', []);

        return parent::getDemandeDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeDonation($demandeDonation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeDonation', [$demandeDonation]);

        return parent::setDemandeDonation($demandeDonation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDonation', []);

        return parent::getTypeDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDonation($typeDonation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDonation', [$typeDonation]);

        return parent::setTypeDonation($typeDonation);
    }

}
