<?php

namespace ProjectBundle\Repository;

/**
 * AideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AideRepository extends \Doctrine\ORM\EntityRepository
{
}
