<?php

namespace ProjectBundle\Repository;

/**
 * AgeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeeRepository extends \Doctrine\ORM\EntityRepository
{
}
