<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ProjectBundle\Entity\Opportunity;
use Doctrine\ORM\Query;

/**
 * OpportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityRepository extends \Doctrine\ORM\EntityRepository
{

public function findEntitiesByString($str)
{
    return $this->getEntityManager()
        ->createQuery(
            'SELECT p 
        FROM ProjectBundle:Opportunity p
        WHERE p.nomop LIKE :str OR p.domaine LIKE :str OR p.descr LIKE :str OR p.jd LIKE :str')
        ->setParameter('str', '%'.$str.'%')
        ->getResult();

}

public function findOPS($domaine,$startDate,$endDate)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
        FROM ProjectBundle:Opportunity p
        WHERE p.domaine LIKE :str1 AND p.startDate > :str2 AND p.endDate < :str3')
            ->setParameter('str1', '%'.$domaine.'%')->setParameter('str2',$startDate)->setParameter('str3',$endDate)
            ->getResult();

    }
}
