<?php

namespace ProjectBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findparticipation($idUser)
    {
        $query= $this->getEntityManager()
            ->createQuery("select m from ProjectBundle:Reservation m WHERE m.idUser=:idUser ")
            ->setParameter('idUser',$idUser)

        ;

        return $query->getResult();
    }


}
