project_aide:
    resource: "@ProjectBundle/Controller/AideController.php"
    type:     annotation

project_agee:
    resource: "@ProjectBundle/Controller/AgeeController.php"
    type:     annotation

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /t

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"


