<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHqaszff\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHqaszff/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHqaszff.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHqaszff\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHqaszff\appProdProjectContainer([
    'container.build_hash' => 'Hqaszff',
    'container.build_id' => '0c730c1e',
    'container.build_time' => 1581457675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHqaszff');
