<?php

namespace ProjectBundle\Repository;

/**
 * PostulationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulationsRepository extends \Doctrine\ORM\EntityRepository
{
}
