<?php

namespace ProjectBundle\Repository;

/**
 * RefugiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugiesRepository extends \Doctrine\ORM\EntityRepository
{
}
