project_opportunity:
    resource: "@ProjectBundle/Resources/config/routing/opportunity.php"
    prefix:   /opportunity

project_postulations:
  resource: "@ProjectBundle/Resources/config/routing/postulations.php"
  prefix:   /postulations

project_homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }
evenement_show:
  path:     /evenement_show
  defaults: { _controller: ProjectBundle:Default:show }

ajax_search:
  path:     /search
  defaults: { _controller: ProjectBundle:Opportunity:search }

vol_menu:
  path:     /volMenu
  defaults: { _controller: ProjectBundle:Default:volMenu }

opportunity_search:
  path:     /opSearch
  defaults: { _controller: ProjectBundle:Opportunity:opSearch }

opportunity_showVol:
  path:     /showVol/{id}
  defaults: { _controller: ProjectBundle:Opportunity:s }

postulations_Success:
  path:     /success
  defaults: { _controller: ProjectBundle:Postulations:success }

postulations_Failure:
  path:     /failure
  defaults: { _controller: ProjectBundle:Postulations:failure }

postulations_accept:
  path:     /accept/{id}
  defaults: { _controller: ProjectBundle:Postulations:accept }

postulations_decline:
  path:     /decline/{id}
  defaults: { _controller: ProjectBundle:Postulations:decline }

entretien_new:
  path:     /reserverEntretien/{idOp}/{idAssoc}
  defaults: { _controller: ProjectBundle:Entretiens:new }

postulation_vol:
  path:     /postulationsVol
  defaults: { _controller: ProjectBundle:Postulations:postulationVol }

entretiens_vol:
  path:     /entretiensVol
  defaults: { _controller: ProjectBundle:Entretiens:entretienVol }




