project_homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }

agee_edit:
    path:     /edit
    defaults: { _controller: ProjectBundle:Agee:edit }

project_per:
    path:   /per
    defaults: { _controller: ProjectBundle:Default:per }

LesVolontaires:
    path:   /LesVolontaires
    defaults: { _controller: ProjectBundle:Default:LesVolontaires }
stat:
    path:   /stat
    defaults: { _controller: ProjectBundle:Default:stat }

statByUser:
    path:   /statByUser
    defaults: { _controller: ProjectBundle:Default:statByUser }

PageStat:
    path:   /PageStat
    defaults: { _controller: ProjectBundle:Default:PageStat }


Calcul:
        path:   /Calcul
        defaults: { _controller: ProjectBundle:Default:Calcul }

CalculByUser:
    path:   /CalculByUser
    defaults: { _controller: ProjectBundle:Default:CalculByUser }